$conn->query("ALTER TABLE users 
    ADD COLUMN IF NOT EXISTS bonus_t_target INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bonus_t_done INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pb_t_target INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pb_t_done INT DEFAULT 0");
